### ISSUE TITLE
Any tips to get transmission working?

### ISSUE THREAD

**Issue by falcomm6** [kelinger/OmniStream#44]
I have tried everything I can think of. Does anyone have a working docker compose for tramission?

Cheers,

**Comment by kelinger** [comment]
Is the 222-transmission.yaml not working?  I know I tested it when building the components list but haven't used it since.

Instead, I'm using a customized Transmission that includes the VPN.  The reason I didn't include it as part of the build is that it is a bit more complex to setup (since you have to also setup your VPN service environmental variables and these change depending on who the VPN provider is).  There's also some "gotchas" in that you need to pre-create certain files on the host before starting up the container the first time, otherwise it ends up creating dummy directories with the same name and things get bad pretty quickly.

The one I'm using on a regular (daily) basis is haugene/transmission-openvpn which can be found [here](https://hub.docker.com/r/haugene/transmission-openvpn).  I'd be happy to share my obfuscated config if that looks like something you want to setup.

**Comment by falcomm6** [comment]
Yes please
. I was going to change the image to that version with the vpn and try get it working after I get the base image working.

Thanks a bunch!

**Comment by kelinger** [comment]
Before you first start this up, you need to run `touch ${LOGS}/transmission.log` to create the log file on your host (should end up in ~/OmniStream/logs/transmission.log).  If you don't, then this file will be created by Docker as a directory.

Additionally, the line `TRANSMISSION_RPC_PASSWORD=xxxxxxxxxxxxx` in my real file actually has the encrypted password (not plain text) for the xxxxxx portion and I'm not sure where I got that.  You could try to use the plain text version in the YAML first.  Transmission (normally, outside of Docker) would take the plain text password from its config file and then rewrite the config with the encrypted password.

Finally, this works for me because I'm using the VPN provider "PRIVADO."  You'd want to use the one that corresponds to your service and the config file (lax-001 in my case) for your nearest server.
```
#
# Transmission - Torrent download engine with VPN
#
  transvpn:
    image: haugene/transmission-openvpn:4.2
    container_name: ${TRANSNAME}
    hostname:  ${TRANSNAME}
    domainname:  ${MYDOMAIN}
    restart: always
    depends_on:
      traefik:
        condition: service_healthy
      omnimount:
        condition: service_healthy
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
      - UMASK_SET=022
      - MEDIA=${MEDIA}
      - HEALTH_CHECK_HOST=google.com
      - TRANSMISSION_WEB_UI=combustion
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=PRIVADO
      - OPENVPN_CONFIG=lax-001
      - OPENVPN_USERNAME=blahblahblah
      - OPENVPN_PASSWORD=xxxxxxxxxxxxxx
      - WEBPROXY_ENABLED=false
      - DROP_DEFAULT_ROUTE=true
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - TRANSMISSION_PORT_FORWARDING_ENABLED=true
      - TRANSMISSION_DOWNLOAD_DIR=/cloud/Downloads/complete
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=50
      - TRANSMISSION_INCOMPLETE_DIR=/cloud/Downloads/incomplete
      - TRANSMISSION_LPD_ENABLED=true
      - TRANSMISSION_MAX_PEERS_GLOBAL=500
      - TRANSMISSION_PEER_LIMIT_GLOBAL=500
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=100
      - TRANSMISSION_PEER_PORT=55955
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_PASSWORD=xxxxxxxxxxxxx
      - TRANSMISSION_RPC_USERNAME=kelinger
    volumes:
      - ${CONFIGS}/${TRANSNAME}/config:/config
      - ${CONFIGS}/${TRANSNAME}/data:/data
      - ${CONFIGS}/${TRANSNAME}/privado:/etc/openvpn/custom
      - ${LOGS}/transmission.log:/data/transmission-home/transmission.log
      - ${LOGS}:/logs
      - ${MERGEMOUNT}:/cloud
      - ${OMNIHOME}/healthchecks/transvpncheck:/transvpncheck
    labels:
      - "omni=${TRANSNAME},${MYDOMAIN},yes,yes,yes"
      - traefik.enable=true
      - traefik.http.routers.transvpn.rule=Host(`${TRANSNAME}.${MYDOMAIN}`)
      - traefik.http.routers.transvpn.tls=true
      - traefik.http.routers.transvpn.tls.certresolver=lets-encrypt
      - traefik.http.services.transvpn.loadbalancer.server.port=9091
    networks:
      - OmniNet
    dns:
      - 8.8.8.8
      - 8.8.4.4
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ["CMD-SHELL", "/transvpncheck"]
      interval: 10s
      timeout: 2s
      retries: 3
```
